spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: embarkx
    password: embarkx
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082
build:
  id: 15
  version: 16.1.2
  name: "demo on Git changed again"
